$BERRYMARKET = [:CHERIBERRY,:CHESTOBERRY,:PECHABERRY,:RAWSTBERRY,:ASPEARBERRY,:LEPPABERRY,:ORANBERRY,:PERSIMBERRY,:LUMBERRY,:SITRUSBERRY,:FIGYBERRY,:WIKIBERRY,:MAGOBERRY,:AGUAVBERRY,:IAPAPABERRY,:POMEGBERRY,:KELPSYBERRY,:QUALOTBERRY,:HONDEWBERRY,:GREPABERRY,:TAMATOBERRY]
$GENERALA = [:POKEBALL,:POTION,:SUPERPOTION,:ANTIDOTE,:PARALYZEHEAL,:AWAKENING,:BURNHEAL,:ICEHEAL,:REPEL]
$GENERALB = [:POKEBALL,:GREATBALL,:POTION,:SUPERPOTION,:ANTIDOTE,:PARALYZEHEAL,:AWAKENING,:BURNHEAL,:ICEHEAL,:FULLHEAL,:REPEL,:SUPERREPEL,:REVIVE,:ETHER]
$GENERALC = [:POKEBALL,:GREATBALL,:ULTRABALL,:POTION,:SUPERPOTION,:HYPERPOTION,:ANTIDOTE,:PARALYZEHEAL,:AWAKENING,:BURNHEAL,:ICEHEAL,:FULLHEAL,:REPEL,:SUPERREPEL,:MAXREPEL,:REVIVE,:ETHER]
$GENERALD = [:POKEBALL,:GREATBALL,:ULTRABALL,:POTION,:SUPERPOTION,:HYPERPOTION,:MAXPOTION,:FULLRESTORE,:ANTIDOTE,:PARALYZEHEAL,:AWAKENING,:BURNHEAL,:ICEHEAL,:FULLHEAL,:REPEL,:SUPERREPEL,:MAXREPEL,:REVIVE,:ETHER,:ELIXIR]
$POKEBALLGUY = [:NETBALL,:DIVEBALL,:NESTBALL,:REPEATBALL,:TIMERBALL,:LUXURYBALL,:DUSKBALL,:HEALBALL,:QUICKBALL]
$TMSELLER1 = [:TM01,:TM02,:TM03,:TM04,:TM05,:TM06,:TM07,:TM08,:TM09,:TM10,:TM11,:TM12,:TM13,:TM14,:TM15,:TM16,:TM17,:TM18,:TM19,:TM20,:TM21,:TM22,:TM23,:TM24,:TM25]
$TMSELLER2 = [:TM26,:TM27,:TM28,:TM29,:TM30,:TM31,:TM32,:TM33,:TM34,:TM35,:TM36,:TM37,:TM38,:TM39,:TM40,:TM41,:TM42,:TM43,:TM44,:TM45,:TM46,:TM47,:TM48,:TM49,:TM50]
$TMSELLER3 = [:TM51,:TM52,:TM53,:TM54,:TM55,:TM56,:TM57,:TM58,:TM59,:TM60,:TM61,:TM62,:TM63,:TM64,:TM65,:TM66,:TM67,:TM68,:TM69,:TM70,:TM71,:TM72,:TM73,:TM74,:TM75]
$TMSELLER4 = [:TM76,:TM77,:TM78,:TM79,:TM80,:TM81,:TM82,:TM83,:TM84,:TM85,:TM86,:TM87,:TM88,:TM89,:TM90,:TM91,:TM92,:TM93,:TM94,:TM95,:TM96,:TM97,:TM98,:TM99,:TM100,:TM101]
$STONESELLER = [:FIRESTONE,:THUNDERSTONE,:WATERSTONE,:LEAFSTONE,:MOONSTONE,:SUNSTONE,:DUSKSTONE,:DAWNSTONE,:SHINYSTONE,:ICESTONE]
$INCENSEGUY = [:LAXINCENSE,:FULLINCENSE,:LUCKINCENSE,:PUREINCENSE,:SEAINCENSE,:WAVEINCENSE,:ROSEINCENSE,:ODDINCENSE,:ROCKINCENSE]
$MISC1 = [:AIRBALLOON,:BRIGHTPOWDER,:EVIOLITE,:FLOATSTONE,:DESTINYKNOT,:ROCKYHELMET,:EJECTBUTTON,:REDCARD,:SHEDSHELL,:SMOKEBALL,:CHOICEBAND,:CHOICESPECS,:CHOICESCARF,:HEATROCK,:DAMPROCK,:SMOOTHROCK,:ICYROCK,:LIGHTCLAY]
$MISC2 = [:SACHET,:WHIPPEDDREAM,:SWEETAPPLE,:TARTAPPLE,:CHIPPEDPOT,:UPGRADE,:DUBIOUSDISC,:PROTECTOR,:ELECTIRIZER,:MAGMARIZER,:REAPERCLOTH,:PRISMSCALE,:OVALSTONE,:ASSAULTVEST,:SOOTHEBELL,:LUCKYEGG]
$MISC3 = [:LIGHTBALL,:LUCKYPUNCH,:METALPOWDER,:QUICKPOWDER,:THICKCLUB,:LEEK,:DEEPSEATOOTH,:DEEPSEASCALE,:DRAGONSCALE]
$MISC4 = [:GRIPCLAW,:BINDINGBAND,:BIGROOT,:BLACKSLUDGE,:LEFTOVERS,:SHELLBELL,:MENTALHERB,:WHITEHERB,:POWERHERB,:ABSORBBULB,:CELLBATTERY,:LIFEORB,:EXPERTBELT,:METRONOME,:MUSCLEBAND,:WISEGLASSES,:RAZORCLAW,:SCOPELENS]
$MISC5 = [:WIDELENS,:ZOOMLENS,:KINGSROCK,:RAZORFANG,:LAGGINGTAIL,:QUICKCLAW,:FOCUSBAND,:FOCUSSASH,:FLAMEORB,:TOXICORB,:STICKYBARB,:IRONBALL,:RINGTARGET,:MACHOBRACE,:POWERWEIGHT,:POWERBRACER,:POWERBELT,:POWERLENS,:POWERBAND,:POWERANKLET]
$POWERBOOSTER = [:CHARCOAL,:MYSTICWATER,:MAGNET,:MIRACLESEED,:NEVERMELTICE,:BLACKBELT,:POISONBARB,:SOFTSAND,:SHARPBEAK,:TWISTEDSPOON,:SILVERPOWDER,:HARDSTONE,:SPELLTAG,:DRAGONFANG,:BLACKGLASSES,:METALCOAT,:SILKSCARF,:PIXIEDUST]
$DRUGDEAL = [:XATTACK,:XDEFENSE,:XSPATK,:XSPDEF,:XSPEED,:XACCURACY,:DIREHIT,:GUARDSPEC,:PPUP,:PPMAX,:HPUP,:PROTEIN,:IRON,:CALCIUM,:ZINC,:CARBOS,:LONELYMINT,:ADAMANTMINT,:NAUGHTYMINT,:BRAVEMINT,:BOLDMINT,:IMPISHMINT,:LAXMINT,:RELAXEDMINT,:MODESTMINT,:MILDMINT,:RASHMINT,:QUIETMINT,:CALMMINT,:GENTLEMINT,:CAREFULMINT,:SASSYMINT,:TIMIDMINT,:HASTYMINT,:JOLLYMINT,:NAIVEMINT,:SERIOUSMINT]
$NURSEA = [:POTION,:POKEBALL]
$NURSEB = [:POTION,:POKEBALL,:GREATBALL]
$NURSEC = [:POTION,:POKEBALL,:GREATBALL,:ULTRABALL]

def pbUnownQuick
  if $Trainer.party[0].species == 201 && $Trainer.party[1].species == 201 && $Trainer.party[2].species == 201 && $Trainer.party[3].species == 201 && $Trainer.party[4].species == 201  # Checks if all Pokemon are Unown
    if $Trainer.party[0].form == 16 && $Trainer.party[1].form == 20 && $Trainer.party[2].form == 8 && $Trainer.party[3].form == 2 && $Trainer.party[4].form == 10
    # Checks if they are in the right order to spell QUICK
    return true
    end
  end
end